
all: build
	#cd ../dist/js/ && ccjs game.js --compilation_level=ADVANCED_OPTIMIZATIONS > game.min.js
	cd ../dist/js/ && google-chrome --load-and-launch-app=/home/ryan/Documents/Development/zombies/dist/js

build:
	haxe build.hxml
